### ISSUE TITLE
Canvas install script fails on first pass (bundle update)

### ISSUE THREAD

**Issue by Thoughtfulmonkey** [FreedomBen/canvas-development-tools#1]
![canvas-script-install](https://cloud.githubusercontent.com/assets/8777899/8158044/7795acd2-1351-11e5-8e37-25c19ca2c1d2.PNG)

First running of the script fails on asset compilation (image included).  Choosing not to continue, running bundle install, and restarting the script allows it to complete successfully.

Note I just run 'bundle install' in the canvas-lms directory, whereas the guide states '$GEM_HOME/bin/bundle install --without mysql'.  And 'bundle exec rails server' to start instead of '$GEM_HOME/bin/bundle exec rails server'.  So I probably have it in the wrong directory.

It's an excellent script though - since I seem to have canvas running with no real knowledge of linux, nodejs or Ruby.

**Comment by ssilverm** [comment]
I had this same issue.  Using Vagrant with an Ubuntu 14 box.  Ended up having to up the memory to 1.5GB, and change Gemfiles.d/test.rb.

test.rb I removed version info for:
  gem 'rspec'
  gem 'rspec-rails'
  gem 'rspec-legacy_formatters'
  gem 'rspec-collection_matchers'

**Comment by FreedomBen** [comment]
Awesome, thanks guys, I'll take a look at it.  @ssilverm are you on Ubuntu 14.04.2?

**Comment by ssilverm** [comment]
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.10
Release:    14.10
Codename:   utopic

**Comment by FreedomBen** [comment]
@Thoughtfulmonkey:  running `'$GEM_HOME/bin/bundle` instead of just `bundle` is only necessary if you don't have `$GEM_HOME/bin` in your `PATH`

**Comment by FreedomBen** [comment]
Ok, it looks like the thrift gem requires a new package on Ubuntu.  I added that to the script, and also fixed a bug that was masking the real problem.

Let me know if you still have any issues.

**Comment by FreedomBen** [comment]
Closing for now.
