### ISSUE TITLE
Why Always Detect Ruby 1.9.3 ?

### ISSUE THREAD

**Issue by kazhuyo** [FreedomBen/canvas-development-tools#13]
Trying install but the process failed with error : 
_

> Your Ruby version is 1.9.3, but your Gemfile specified 2.3.1
> Error installing required gems.  Please run 'bundle install' manually and try again

_
i'm trying install ruby 2.3.1 manual, but it's still detect ruby 1.9.3 
what should i do ?

**Comment by FreedomBen** [comment]
You'll need to make sure that `which ruby` finds ruby 2.3.1.  You can do that through PATH manipulation (make sure 2.3.1's path shows up first) or by removing 1.9.3.

I personally use `chruby` for this:  https://github.com/postmodern/chruby
You'll probably want to pair it with `ruby-install` for easy use:  https://github.com/postmodern/ruby-install#readme

**Comment by kazhuyo** [comment]
the installation is from fresh machine, I think the code must be updated, remove the line with "apt-get -y install ruby" because default repo will install ruby 1.9.3

**Comment by FreedomBen** [comment]
The ruby version that apt-get installs will depend on the distro.  It shouldn't interfere with chruby, rbenv, and rvm if you're using a ruby version manager (which you'll need to do if you're on an ubuntu version that ships an old ruby, which appears to be the case for you)

**Comment by kazhuyo** [comment]
this problem appears if user using this CODES.sh with fresh ubuntu installation.
so the first thing we need is intall chruby first before running the code ? or using rvm ?

**Comment by FreedomBen** [comment]
yes, installing chruby first before running CODES.sh is the recommended path.  It's totally fine if you've already run it once tho.  Just install chruby and switch to your desired ruby version, then rerun CODES.sh.  CODES will use whatever ruby is first in your PATH (which you can test with `which ruby` and also `ruby -v`)

**Comment by kazhuyo** [comment]
Solved, it's a good idea if you update the script code install chruby too.

**Comment by FreedomBen** [comment]
Yeah it does actually do chruby for Arch Linux and macOS, but not on ubuntu and fedora since they don't have it in their repos.  Not too bad to do tho, just need some time.
