### ISSUE TITLE
Ubuntu 14.04.03 install fails at bundler gems installation

### ISSUE THREAD

**Issue by danieldbower** [FreedomBen/canvas-development-tools#6]
With clean installation of Ubuntu 14.04 (all current updates applied), the installer fails on bundler gems:

Installing the bundle gem version 1.10.5
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions into the /var/lib/gems/1.9.1 directory.
Installing bundler without sudo failed.  Trying again with sudo...
Successfully installed bundler-1.10.5
1 gem installed
Installing ri documentation for bundler-1.10.5...
Installing RDoc documentation for bundler-1.10.5...
Bundler is installed
Installing bundler gems with bundle install (but no mysql)
Making sure the gem location is in PATH
Your Ruby version is 1.9.3, but your Gemfile specified 2.1.6
Error installing required gems.  Please run 'bundle install' manually and try again

I'm going to figure out how to install ruby manually, and then rerun the script.  Hopefully it should continue where it left off.

**Comment by danieldbower** [comment]
I installed Ruby manually using the rbenv tutorial here:  https://gorails.com/setup/ubuntu/14.04 and the install appears to be continuing.

**Comment by FreedomBen** [comment]
Thanks @danieldbower .  I should probably update the script to give a more helpful error message.  Canvas now requires ruby >=2.1.0 so bundle install will fail without it.
