### ISSUE TITLE
NodeJS not Installed

### ISSUE THREAD

**Issue by lunalunaki** [FreedomBen/canvas-development-tools#9]
Hi,

I have been trying to install Canvas through your development tools but for some reason it is not recognizing that I have NodeJS already installed. I have also completely uninstalled it seeing to let it install for me but it just comes to a full stop asking me to manually install it.

edit: nevermind, Canvas only supports older versions of node. I just switched node to 0.12 using nvm

**Comment by FreedomBen** [comment]
Awesome, glad you got it figured out.
